// Events
export const EVENTS_LOADED = "EVENTS_LOADED"
export const DISABLED_EVENTS_LOADED = "DISABLED_EVENTS_LOADED"
export const DISABLE_EVENT = "DISABLE_EVENT"

// Jobs
export const JOBS_LOADED = "JOBS_LOADED"

// Notifications
export const LOCAL_PERMISSIONS_LOADED = "LOCAL_PERMISSIONS_LOADED"
export const PUSH_NOTIFICATIONS_REGISTER_LOADING = "PUSH_NOTIFICATIONS_REGISTER_LOADING"
export const PUSH_NOTIFICATIONS_REGISTER_LOADED = "PUSH_NOTIFICATIONS_REGISTER_LOADED"
export const BROADCAST_INCOMING_NOTIFICATION = "BROADCAST_INCOMING_NOTIFICATION"
export const RESET_INCOMING_NOTIFICATION = "RESET_INCOMING_NOTIFICATION"
// export const PUSH_NOTIFICATIONS_REGISTER_SUCCESS = "PUSH_NOTIFICATIONS_REGISTER_SUCCESS"
// export const PUSH_NOTIFICATIONS_REGISTER_FAILURE = "PUSH_NOTIFICATIONS_REGISTER_FAILURE"

// Reminders
export const LOCAL_REMINDERS_LOADED = "LOCAL_REMINDERS_LOADED"
export const LOCAL_REMINDERS_LOADING = "LOCAL_REMINDERS_LOADING"
